version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
      timezone: "Asia/Kolkata"
    assignees:
      - "Subhransu-De"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
      timezone: "Asia/Kolkata"
    assignees:
      - "Subhransu-De"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
      timezone: "Asia/Kolkata"
    assignees:
      - "Subhransu-De"
