name: Docker Bake CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        run: |
          docker buildx bake --print
          docker buildx bake

      - name: Verify Images
        run: |
          docker images | grep "myapp.*latest-amd64" || exit 1
          docker images | grep "myapp.*${COMMIT_SHA}-amd64" || exit 1
          docker images | grep "myapp.*latest-arm64" || exit 1
          docker images | grep "myapp.*${COMMIT_SHA}-arm64" || exit 1
